[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
Documenter = "1"
